/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

allprojects {
    repositories {
        jcenter()
    }
}

subprojects {
    version = "1.0"
}


task<Copy>("copyConfig") {
    from (file("$buildDir/../micros-config/build/libs/micros-config-0.0.1-SNAPSHOT.jar").absoluteFile)
    into (file("$buildDir/../dockers/config-service").absoluteFile)
}
task<Copy>("copyEureka") {
    from (file("$buildDir/../micros-eureka/build/libs/micros-eureka-0.0.1-SNAPSHOT.jar").absoluteFile)
    into (file("$buildDir/../dockers/eureka").absoluteFile)
}

task<Copy>("copyPing") {
    from (file("$buildDir/../services/build/libs/services-0.0.1-SNAPSHOT.jar").absoluteFile)
    into (file("$buildDir/../dockers/ping").absoluteFile)
}

task<Copy>("copyPong") {
    from (file("$buildDir/../services/build/libs/services-0.0.1-SNAPSHOT.jar").absoluteFile)
    into (file("$buildDir/../dockers/pong").absoluteFile)
}

task("copyArtifacts")
        .dependsOn("copyConfig", "copyEureka", "copyPing", "copyPong")