import java.net.URI

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

plugins {
    `kotlin-dsl`
}

allprojects {
    repositories {
        jcenter()
    }

    buildscript {
        val kotlinVersion = "1.2.71"
        val springBootVersion = "2.1.1.RELEASE"

        repositories {
            mavenCentral()
        }

        dependencies {
            implementation("org.springframework.boot:spring-boot-gradle-plugin:$springBootVersion")
            classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
            classpath("org.jetbrains.kotlin:kotlin-allopen:$kotlinVersion")
        }

    }
}

val springCloudVersion = "Greenwich.RC1"

subprojects {
    version = "1.0"
}


dependencies {
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

}

dependencyManagement {
    imports {
        mavenBom = "org.springframework.cloud:spring-cloud-dependencies:$springCloudVersion"
    }
}

repositories {
    mavenCentral()
    maven { url = URI.create("https://repo.spring.io/milestone") }
}


