version: '3'

services:

  config:
    build: ./config-service
    ports:
      - "8888:8888"

    volumes:
      - /dvlp/Development/workspace/Roadmap/micros/dockers/config-service/config.prop:/config

    networks:
      micronet:
        aliases:
          - config


  eureka:
    build: ./eureka
    ports:
      - "1111:1111"

    networks:
      micronet:
        aliases:
          - eureka

    depends_on:
    - config


  pong:
    build: ./pong
    #    ports:
    #  - "8080:8080"

        #    container_name: pong-service

    depends_on:
      - config
      - eureka

    networks:
      - micronet

  ping:
    build: ./ping
    #   ports:
    #   - "8081:8081"

    networks:
      - micronet

    depends_on:
      - pong
      - eureka

networks:
  micronet:




 
