server:
  port: 1111

#eureka:
#  instance:
#    host: localhost
#    hostname: roadmap
#    port: 1111

eureka:

  instance:
    hostname: localhost

  client:
    registerWithEureka: false
    fetchRegistry: false

#      serviceUrl:
#        defaultZone: ${EUREKA_URI:http://${eureka.instance.host}:${server.port}/eureka}
