server:
  port: 1111

spring:
  application:
    name: eureka-server

  cloud:
    config: http://localhost:8888

eureka:

  instance:
    hostname: localhost
    preferIpAddress: true

  client:
    registerWithEureka: false
    fetchRegistry: false

    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${eureka.instance.host}:${server.port}/eureka}
