server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://6.6.6.25/~/git/micros-config
          clone-on-start: true

security:
  user:
    name: bot
    password: 1D0n0S&