server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: /dvlp/Development/workspace/Roadmap/micros/dockers/config-service/config.prop/
          clone-on-start: true

security:
  user:
    name: config
    password: micro-config